name: Release
run-name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag / Version number"
        required: true
      image-folder-name:
        description: "Image folder name (for replacing image paths embedded in the README)"
        required: false
        default: "images"
      is-dry-run:
        description: "Dry-run (do not publish, only test build)"
        type: boolean

permissions:
  contents: write # required for pushing to the repository and creating releases

env:
  changelog: CHANGELOG.md
  thunderstore-config: thunderstore.toml
  build-dir: build
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  release:
    name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check input tag format
        run: |
          if ! echo "${{ inputs.tag }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "::error title=Invalid package version number::Version numbers must follow the Major.Minor.Patch format (e.g. 1.45.320)."
            exit 1
          fi

      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true

      - name: Rotate unreleased section in changelog
        uses: baynezy/ChangeLogger.Action@6e3ad430f08e13698bb01027a13ba4349b0143cc
        with:
          tag: ${{ inputs.tag }}
          log-path: ${{ env.changelog }}

      - name: Rotate version in Thunderstore CLI config
        run: |
          sed -i 's/versionNumber = ".*"/versionNumber = "${{ inputs.tag }}"/' ${{ env.thunderstore-config }}

      - name: Replace relative image paths with absolute paths in README
        run: |
          sed -i 's#](\(\./\)\?${{ inputs.image-folder-name }}/#](https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/raw/${{ github.event.repository.default_branch }}/${{ inputs.image-folder-name }}/#g' README.md

      - name: Install Thunderstore CLI
        run: dotnet tool install -g tcli

      - name: Build package
        run: |
          tcli build
          ARTIFACT_NAME=$(find "${{ env.build-dir }}" -type f -printf "%f\n")
          echo "artifact-name=${ARTIFACT_NAME}" >> "$GITHUB_ENV"
          echo "artifact-path=${{ env.build-dir }}/${ARTIFACT_NAME}" >> "$GITHUB_ENV"

      - name: Upload artifact to workflow
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-path }}
          retention-days: 1

      - name: Publish package
        if: ${{ !inputs.is-dry-run }}
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
        run: tcli publish --file ${{ env.artifact-path }}

      - name: Tag and push to repository
        if: ${{ !inputs.is-dry-run }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.changelog }} ${{ env.thunderstore-config }}
          git commit --message "Release ${{ inputs.tag }}"
          git tag ${{ inputs.tag }} --annotate --message "Release ${{ inputs.tag }}"
          git push origin HEAD:${{ github.ref_name }} --tags

      - name: Create release and upload artifact
        if: ${{ !inputs.is-dry-run }}
        run: |
          gh release create \
            '${{ inputs.tag }}' \
            '${{ env.artifact-path }}' \
            --title '${{ inputs.tag }}' \
            --repo '${{ github.repository }}' \
            --target '${{ github.ref_name }}' \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
