name: Release
run-name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag / Version number"
        required: true
      is-dry-run:
        description: "Dry-run (do not publish, only test build)"
        type: boolean

permissions:
  contents: write # required for pushing to the repository and creating releases

env:
  changelog: CHANGELOG.md
  source-dir: src/
  artifact-name: hades2-mod-template.zip
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  release:
    name: ${{ format('{0} {1}', inputs.is-dry-run && 'Dry-run' || 'Release', inputs.tag) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check input tag format
        run: |
          if ! echo "${{ inputs.tag }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "::error title=Invalid package version number::Version numbers must follow the Major.Minor.Patch format (e.g. 1.45.320)."
            exit 1
          fi

      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true

      - name: Rotate unreleased section in changelog
        uses: baynezy/ChangeLogger.Action@6e3ad430f08e13698bb01027a13ba4349b0143cc
        with:
          tag: ${{ inputs.tag }}
          log-path: ${{ env.changelog }}

      - name: Build template
        run: |
          cd ${{ env.source-dir }}
          zip ../${{ env.artifact-name }} -r .

      - name: Upload artifact to workflow
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-name }}
          retention-days: 1

      - name: Push updated files to repository and tag
        if: ${{ !inputs.is-dry-run }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.changelog }}
          git commit --message "Release ${{ inputs.tag }}"
          git tag ${{ inputs.tag }} --annotate --message "Release ${{ inputs.tag }}"
          git push origin HEAD:${{ github.ref_name }} --tags

      - name: Create release and upload artifact
        if: ${{ !inputs.is-dry-run }}
        run: |
          gh release create \
            '${{ inputs.tag }}' \
            '${{ env.artifact-name }}' \
            --title '${{ inputs.tag }}' \
            --repo '${{ github.repository }}' \
            --target '${{ github.ref_name }}' \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
